ServerName localhost
<IfModule mod_headers.c>
    Header always set Strict-Transport-Security "max-age=15552000"
</IfModule>
<IfModule mpm_prefork_module>
    StartServers 2
    MinSpareServers 2
    MaxSpareServers 4
    ServerLimit 8
    MaxRequestWorkers 8
    MaxConnectionsPerChild 1000
</IfModule>
